package com.tappy.pos.model.enums;

public enum ActivityAction {
    LOGIN, LOGOUT,
    TENANT_CREATED, TENANT_UPDATED,
    AGENT_CREATED, AGENT_UPDATED,
    FEEDBACK_REVIEWED,
    ORDER_CREATED, ORDER_COMPLETED, ORDER_CANCELLED, ORDER_VOIDED,
    ORDER_CONFIRMED, ORDER_REJECTED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    PRODUCT_IMAGE_UPDATED, PRODUCT_IMAGE_DELETED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED,
    EMPLOYEE_CREATED, EMPLOYEE_UPDATED,
    VENDOR_CREATED, VENDOR_UPDATED,
    PURCHASE_ORDER_CREATED, PURCHASE_ORDER_RECEIVED,
    INVENTORY_ADJUSTED,
    EXPENSE_CREATED,
    PAWN_CREATED, PAWN_UPDATED, PAWN_DELETED, PAWN_CANCEL, PAWN_FORFEIT, PAWN_REDEEMED, PAWN_EXTEND, PAWN_REQUEST_MONEY,
    USER_CREATED, USER_AVATAR_UPDATED, USER_AVATAR_DELETED,
    SALARY_GENERATED, SALARY_APPROVED, SALARY_PAID,
    SALARY_ADVANCE_CREATED, SALARY_ADVANCE_DELETED,
    MOBILE_EVENT
}
