package com.knp.model.enums;

public enum ActivityAction {
    LOGIN,
    ORDER_CREATED, ORDER_COMPLETED, ORDER_CANCELLED, ORDER_VOIDED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED
}
