package com.knp.model.enums;

public enum ActivityAction {
    LOGIN,
    ORDER_CREATED, ORDER_COMPLETED, ORDER_CANCELLED, ORDER_VOIDED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED,
    PAWN_CREATED, PAWN_UPDATED, PAWN_DELETED, PAWN_CANCEL, PAWN_FORFEIT, PAWN_REDEEMED, PAWN_EXTEND, PAWN_REQUEST_MONEY,
    USER_CREATED, VENDOR_CREATED
}
